"""Ticker-to-company-name mapping for all tracked stocks."""

TICKER_NAMES: dict[str, str] = {
    "AAPL": "Apple",
    "ABBV": "AbbVie",
    "ADBE": "Adobe",
    "AAL": "American Airlines",
    "AMD": "AMD",
    "AMZN": "Amazon",
    "BA": "Boeing",
    "BAC": "Bank of America",
    "C": "Citigroup",
    "CCL": "Carnival",
    "COST": "Costco",
    "CSCO": "Cisco",
    "CVX": "Chevron",
    "DAL": "Delta Air Lines",
    "DIS": "Disney",
    "DOCU": "DocuSign",
    "ETSY": "Etsy",
    "F": "Ford",
    "FDX": "FedEx",
    "GE": "GE Aerospace",
    "GM": "General Motors",
    "GOOGL": "Alphabet",
    "GS": "Goldman Sachs",
    "HCA": "HCA Healthcare",
    "INTC": "Intel",
    "JNJ": "Johnson & Johnson",
    "JPM": "JPMorgan Chase",
    "KO": "Coca-Cola",
    "LMT": "Lockheed Martin",
    "META": "Meta Platforms",
    "MSFT": "Microsoft",
    "NFLX": "Netflix",
    "NKE": "Nike",
    "NVDA": "NVIDIA",
    "PEP": "PepsiCo",
    "PFE": "Pfizer",
    "PINS": "Pinterest",
    "PLTR": "Palantir",
    "PYPL": "PayPal",
    "RBLX": "Roblox",
    "ROKU": "Roku",
    "SBUX": "Starbucks",
    "SHOP": "Shopify",
    "SNAP": "Snap",
    "T": "AT&T",
    "TGT": "Target",
    "TSLA": "Tesla",
    "TWTR": "Twitter",
    "UAL": "United Airlines",
    "UBER": "Uber",
    "UNH": "UnitedHealth",
    "V": "Visa",
    "VZ": "Verizon",
    "WBA": "Walgreens",
    "WFC": "Wells Fargo",
    "WMT": "Walmart",
    "XOM": "ExxonMobil",
    "ZM": "Zoom",
}
